// ThumbFish.idl : IDL source for ThumbFish
//

// This file will be processed by the MIDL tool to
// produce the type library (ThumbFish.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(AAA59AED-6460-487D-BD22-854128D97F75),
	pointer_default(unique)
]
interface IPreview : IUnknown
{
};

[
	object,
	uuid(1CBE7B28-8E2B-48EE-AA11-0C3D294ECA37),
	pointer_default(unique)
]
interface IThumbnail : IUnknown
{
};

[
	object,
	uuid(E0989131-E810-4FA6-8472-B6B2806F5D87),
	pointer_default(unique)
]
interface ISearch : IUnknown
{
};

[
	object,
	uuid(83C2225A-DEB5-4809-82A4-2025EE373867),
	pointer_default(unique)
]
interface IContextMenuHandler : IUnknown
{
};

[
	uuid(506A7C6B-81F0-459A-8A31-6479713762D0),
	version(1.0),
]
library ThumbFishLib
{
	importlib("stdole2.tlb");
	[
		uuid(A9433902-9E0E-4519-A499-CB02E5A3E972)
	]
	coclass Preview
	{
		[default] interface IPreviewHandler;
	};
	[
		uuid(F746DF9F-8C76-4E97-B7C9-049FDD625E72)
	]
	coclass Thumbnail
	{
		[default] interface IThumbnailProvider;
	};
	[
		uuid(3D36EF79-CA3B-4AED-AB29-FB13BAB9BB08)
	]
	coclass Search
	{
		[default] interface IFilter;
	};
	[
		uuid(D2DE2A6B-8D18-4B08-BD80-64B207964A53),
	]
	coclass ContextMenuHandler
	{
		[default] interface IContextMenuHandler;
	};
};

import "shobjidl.idl";
import "thumbcache.idl";
import "filter.idl";
